#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GLSLANG="$ROOT_DIR/tools/glslang/bin/glslang"

if [[ ! -x "$GLSLANG" ]]; then
  echo "glslang not found at $GLSLANG, running fetch_tools.sh..."
  "$ROOT_DIR/scripts/fetch_tools.sh"
fi

# 1. Compile GLSL shaders to SPIR-V
OUT_SHADERS="$ROOT_DIR/build/shaders"
mkdir -p "$OUT_SHADERS"

echo "==> Compiling GLSL compute shaders to SPIR-V..."
for comp in "$ROOT_DIR"/shaders/*.comp; do
  base="$(basename "$comp" .comp)"
  "$GLSLANG" -V --target-env vulkan1.3 -I"$ROOT_DIR/shaders" "$comp" -o "$OUT_SHADERS/${base}.spv"
done
echo "Compiled $(ls "$OUT_SHADERS"/*.spv | wc -l | tr -d ' ') shaders to $OUT_SHADERS"

# 2. PTX kernels generated by Python emitters into build/ptx
PTX_OUT="$ROOT_DIR/build/ptx"
mkdir -p "$PTX_OUT"

echo "==> Generating PTX kernels..."
PYTHON="${PYTHON:-python3}"

for k in 64 128 256; do
  "$PYTHON" "$ROOT_DIR/scripts/ptx/mlp_e4m3.py" $k "$PTX_OUT/mlp_e4m3_K$k.ptx" 3 1 1 > /dev/null
done

for c in 64 128 256 512; do
  "$PYTHON" "$ROOT_DIR/scripts/ptx/qkv_e4m3.py" $c "$PTX_OUT/qkv_e4m3_K$c.ptx" 80 > /dev/null
done

for k in 32 64 128 256 512 1024; do
  for f in 5 13 4 8 6; do
    "$PYTHON" "$ROOT_DIR/scripts/ptx/gemm2_e4m3.py" $k $f "$PTX_OUT/gemm2_e4m3_K${k}_f$f.ptx" > /dev/null
  done
done

for cfg in "64 4 0" "128 4 0" "256 3 80" "256 4 64"; do
  set -- $cfg
  c=$1; r=$2; s=$3
  "$PYTHON" "$ROOT_DIR/scripts/ptx/ffn_e4m3.py" $c $r "$PTX_OUT/ffn_e4m3_C${c}_R${r}.ptx" $s > /dev/null
  "$PYTHON" "$ROOT_DIR/scripts/ptx/ffn_e4m3.py" $c $r "$PTX_OUT/ffn_e4m3_C${c}_R${r}_proj.ptx" $s 1 > /dev/null
done

for cfg in "4096 1 32 4" "1024 0 16 2" "1024 1 8 4" "1024 0 8 4"; do
  set -- $cfg
  k=$1; f=$2; p=$3; s=$4
  "$PYTHON" "$ROOT_DIR/scripts/ptx/gemmt_e4m3.py" $k $f $p $s "$PTX_OUT/gemmt_e4m3_K${k}_f${f}_p${p}_s${s}.ptx" > /dev/null
done

for cfg in "4 4" "2 8" "4 8"; do
  set -- $cfg
  s=$1; f=$2
  "$PYTHON" "$ROOT_DIR/scripts/ptx/reduce_e4m3.py" $s $f "$PTX_OUT/reduce_e4m3_s${s}_f${f}.ptx" > /dev/null
done

for cfg in "1024 6 1" "4096 5 4" "1024 8 2" "1024 5 4"; do
  set -- $cfg
  k=$1; f=$2; s=$3
  "$PYTHON" "$ROOT_DIR/scripts/ptx/gemmv_e4m3.py" $k $f $s "$PTX_OUT/gemmv_e4m3_K${k}_f${f}_s${s}.ptx" > /dev/null
  "$PYTHON" "$ROOT_DIR/scripts/ptx/gemmv_e4m3.py" $k $f $s "$PTX_OUT/gemmv_e4m3_K${k}_f${f}_s${s}_m96.ptx" 4 6 0 0 0 96 > /dev/null
done

for padded in 64 128 192 256; do
  "$PYTHON" "$ROOT_DIR/scripts/ptx/global_attention_e4m3.py" $padded "$PTX_OUT/global_attention_e4m3_p${padded}.ptx" > /dev/null
done

"$PYTHON" "$ROOT_DIR/scripts/ptx/global_attention_stream_e4m3.py" normalize "$PTX_OUT/global_normalize_e4m3.ptx" > /dev/null
"$PYTHON" "$ROOT_DIR/scripts/ptx/global_attention_stream_e4m3.py" attention "$PTX_OUT/global_attention_stream_e4m3.ptx" 4 > /dev/null

for cfg in "512 4" "512 5" "512 13" "256 5" "4096 5" "1024 8" "1024 5"; do
  set -- $cfg
  k=$1; f=$2
  "$PYTHON" "$ROOT_DIR/scripts/ptx/gemmv_e4m3.py" $k $f 1 "$PTX_OUT/gemmv_e4m3_K${k}_f${f}_s1_m96.ptx" 4 6 0 0 0 96 > /dev/null
done

for f in 2 66 74 130 48; do
  "$PYTHON" "$ROOT_DIR/scripts/ptx/block32_e4m3.py" $f "$PTX_OUT/block32_e4m3_f${f}.ptx" > /dev/null
done

echo "Generated $(ls "$PTX_OUT"/*.ptx | wc -l | tr -d ' ') PTX kernels into $PTX_OUT"
